language: node_js

node_js:
  - 10

cache:
  yarn: true
  directories:
    - .firebase
    - node_modules

script:
  - sed -i "s/GIT_COMMIT_HASH/$(git rev-parse --short HEAD)/" web/src/environments/*
  - yarn --cwd web/ build --prod

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
