[package]
name = "holostats-script"
version = "0.1.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
chrono = { version = "0.4.9", features = ["serde"] }
futures-preview = "=0.3.0-alpha.18"
isahc = { version = "0.7.3", default-features = false, features = ["json", "http2", "static-curl"] }
serde = { version = "1.0.100", features = ["derive"] }
serde_json = "1.0.40"
url = "2.1.0"

[profile.release]
lto = true

[[bin]]
name = "stream_list"
path = "src/stream_list.rs"

[[bin]]
name = "stream_stat"
path = "src/stream_stat.rs"

[[bin]]
name = "vtuber_stat"
path = "src/vtuber_stat.rs"
