name: Angular

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Add yarn global bin to path
        run: echo "::add-path::$(yarn global bin)"

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Run Prettier
        working-directory: web
        run: |
          yarn global add prettier
          prettier --check --ignore-path .gitignore 'src/**/*.{ts,js,json.html,scss}'

      - name: Build web
        if: github.ref == 'refs/heads/master'
        working-directory: web
        run: |
          yarn install
          sed -i "s/GIT_COMMIT_HASH/$(git rev-parse --short HEAD)/" src/environments/*
          yarn build --prod

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        working-directory: web
        run: rsync -avzzP dist/browser/* rsync://ci@${{ secrets.RSYNC_HOST }}/web
        env:
          RSYNC_PASSWORD: ${{ secrets.RSYNC_PASSWORD }}
