name: Angular

on: [push, pull_request]

defaults:
  run:
    working-directory: web

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Add yarn global bin to path
        run: echo "::add-path::$(yarn global bin)"

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Run Prettier
        run: |
          yarn global add prettier
          prettier --check --ignore-path .gitignore 'src/**/*.{ts,js,json.html,scss}'

      - name: Build
        run: |
          yarn install
          sed -i "s/GIT_COMMIT_HASH/$(git rev-parse --short HEAD)/" src/environments/*
          yarn ng run holostats:app-shell
          yarn ng run holostat:workers

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/master'

      - name: Production build
        run: |
          yarn ng run holostats:app-shell:production
          yarn ng run holostats:workers:production

      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "prod"
