name: Rust

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Initialize database
        working-directory: server
        run: psql -f sql/schema.sql
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache target/
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Format
        run: cargo fmt --manifest-path server/Cargo.toml -- --check

      - name: Run Test
        working-directory: server
        run: cargo test
        env:
          YOUTUBE_API_KEY0: YOUTUBE_API_KEY0
          YOUTUBE_API_KEY1: YOUTUBE_API_KEY1
          DATABASE_URL: postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
          PUBSUBHUBBUB_URL: PUBSUBHUBBUB_URL

      - name: Build
        if: github.ref == 'refs/heads/master'
        working-directory: server
        run: |
          cargo build --release
          strip target/release/{server,subscribe,stream_stat,channel_stat}
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
          YOUTUBE_API_KEY0: ${{ secrets.YOUTUBE_API_KEY0 }}
          YOUTUBE_API_KEY1: ${{ secrets.YOUTUBE_API_KEY1 }}
          PUBSUBHUBBUB_URL: ${{ secrets.PUBSUBHUBBUB_URL }}

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        working-directory: server
        run: rsync -avzzP target/release/{server,subscribe,stream_stat,channel_stat} rsync://ci@${{ secrets.RSYNC_HOST }}/bin
        env:
          RSYNC_PASSWORD: ${{ secrets.RSYNC_PASSWORD }}
